# Create the greetd home directory if it doesn't exist
d /var/lib/greetd 0750 greetd greetd - -

# Ensure the config file is linked in /etc/greetd
L+ /etc/greetd/config.toml - - - - /usr/etc/greetd/config.toml
