# Crea un link simbolico da /opt/helium verso /usr/lib/helium all'avvio.
# Necessario per i sistemi Atomic dove /opt è un link a /var/opt e i file nell'immagine verrebbero nascosti.
L+ /opt/helium - - - - /usr/lib/helium
