# Crea un link simbolico per Helium per permettergli di trovarsi come browser predefinito
# L+ crea il link e sovrascrive se esiste già
L+ /usr/local/share/applications/helium.desktop - - - - /var/lib/flatpak/exports/share/applications/com.github.ShyVortex.Helium.desktop
