# Crea un link simbolico per Helium (net.imput.helium) per permettergli di trovarsi come browser predefinito
L+ /usr/local/share/applications/helium.desktop - - - - /var/lib/flatpak/exports/share/applications/net.imput.helium.desktop
